### ISSUE TITLE
Group Capstone: Set up Kanban board

### ISSUE THREAD

**Issue by TEMESGEN-G25** [TEMESGEN-G25/MovieSpace#22]
[Github project](https://github.com/NatiG25/JS-capstone/projects/2)

- There are two people for this team.

**Comment by omar-labana** [comment]
Hi team, 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] Each card should be assigned to a team member, currently, all cards have the status "Assignees: No one assigned". Kindly update your cards.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TEMESGEN-G25** [comment]
Thank you for your suggestion. I already implemented and added an assignee for each task.

**Comment by ShoiraTa** [comment]
## **STATUS: APPROVED  🟢 ** 
------
### Hi team, 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
